import css from 'styled-jsx/css';

export default css`

.upload-license-copy {
  background: none;
  border: none;
  color: #0C97F9;
  font-size: 12px;
  font-weight: 500;
  line-height: 18px;
}

.inputFile {
  display: none;
}

.icon-upload {
  float: left;
  margin-top: 4px;
  padding-left: 10px;
  width: 10px;
  height: 10px;
  fill: #0C97F9;
  background: no-repeat;
  background-image: url("data:image/svg+xml;charset=utf8,%3C!-- Generated by IcoMoon.io --%3E%3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 10 10'%3E%3Ctitle%3Eupload%3C/title%3E%3Cpath d='M8.75 5.833c-0.25 0-0.417 0.167-0.417 0.417v1.667c0 0.25-0.167 0.417-0.417 0.417h-5.833c-0.25 0-0.417-0.167-0.417-0.417v-1.667c0-0.25-0.167-0.417-0.417-0.417s-0.417 0.167-0.417 0.417v1.667c0 0.708 0.542 1.25 1.25 1.25h5.833c0.708 0 1.25-0.542 1.25-1.25v-1.667c0-0.25-0.167-0.417-0.417-0.417z' fill='%230C97F9'%3E%3C/path%3E%3Cpath d='M3.208 3.625l1.375-1.375v4c0 0.25 0.167 0.417 0.417 0.417s0.417-0.167 0.417-0.417v-4l1.375 1.375c0.083 0.083 0.167 0.125 0.292 0.125s0.208-0.042 0.292-0.125c0.167-0.167 0.167-0.417 0-0.583l-2.083-2.083c-0.042-0.042-0.083-0.083-0.125-0.083-0.083-0.042-0.208-0.042-0.333 0-0.042 0.042-0.083 0.042-0.125 0.083l-2.083 2.083c-0.167 0.167-0.167 0.417 0 0.583s0.417 0.167 0.583 0z' fill='%230C97F9'%3E%3C/path%3E%3C/svg%3E");
}

.box {
  display: flex;
  align-items: center;
  width: 335px;
  border-radius: 4px;
  background-color: #FFFFFF;
  box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.1);
}

.filename {
  width: 300px;
  color: #F2F2F2;
  font-size: 14px;
  font-weight: 500;
  line-height: 18px;
}

.icons {
  height: 21px;
  width: 52px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.med {
  height: 15px;
  width: 15px;
  margin: 13px 12px 13px 15px;
  background-size: 14px;
  background-image: url("data:image/svg+xml;charset=utf8,%3C?xml version='1.0' encoding='UTF-8'?%3E%3Csvg width='19px' height='21px' viewBox='0 0 19 21' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3C!-- Generator: sketchtool 49.1 (51147) - http://www.bohemiancoding.com/sketch --%3E%3Ctitle%3E8A09A359-1607-4918-A199-DF7936EF3336%3C/title%3E%3Cdesc%3ECreated with sketchtool.%3C/desc%3E%3Cdefs%3E%3Cpath d='M3.5,3.5 C2.94771525,3.5 2.5,3.94771525 2.5,4.5 L2.5,17.5 C2.5,18.0522847 2.94771525,18.5 3.5,18.5 L15.5,18.5 C16.0522847,18.5 16.5,18.0522847 16.5,17.5 L16.5,4.5 C16.5,3.94771525 16.0522847,3.5 15.5,3.5 L3.5,3.5 Z M3.5,1.5 L15.5,1.5 C17.1568542,1.5 18.5,2.84314575 18.5,4.5 L18.5,17.5 C18.5,19.1568542 17.1568542,20.5 15.5,20.5 L3.5,20.5 C1.84314575,20.5 0.5,19.1568542 0.5,17.5 L0.5,4.5 C0.5,2.84314575 1.84314575,1.5 3.5,1.5 Z M7,0.5 L12,0.5 C12.8284271,0.5 13.5,1.17157288 13.5,2 L13.5,4 C13.5,4.82842712 12.8284271,5.5 12,5.5 L7,5.5 C6.17157288,5.5 5.5,4.82842712 5.5,4 L5.5,2 C5.5,1.17157288 6.17157288,0.5 7,0.5 Z M6.9761486,10.5542814 C6.63845919,10.2324554 6.09095647,10.2324554 5.75326706,10.5542814 C5.41557765,10.8761075 5.41557765,11.3978906 5.75326706,11.7197167 L8.67059538,14.5 L13.2467329,10.192519 C13.5844224,9.87069299 13.5844224,9.34890987 13.2467329,9.02708382 C12.9090435,8.70525777 12.3615408,8.70525777 12.0238514,9.02708382 L8.67059538,12.1691296 L6.9761486,10.5542814 Z' id='path-1'%3E%3C/path%3E%3C/defs%3E%3Cg id='Page-1' stroke='none' stroke-width='1' fill='none' fill-rule='evenodd'%3E%3Cg id='Acc-details-filled' transform='translate(-927.000000, -1696.000000)'%3E%3Cg id='Group-5' transform='translate(909.000000, 169.000000)'%3E%3Cg id='Group-4-Copy-2' transform='translate(4.000000, 1515.000000)'%3E%3Cg id='Group-7' transform='translate(14.000000, 12.000000)'%3E%3Cg id='Group-6'%3E%3Cg id='Icons/Documents/Medical-Records'%3E%3Cg id='icon'%3E%3Cmask id='mask-2' fill='white'%3E%3Cuse xlink:href='%23path-1'%3E%3C/use%3E%3C/mask%3E%3Cuse id='medical-records' fill='%230C97F9' fill-rule='nonzero' xlink:href='%23path-1'%3E%3C/use%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
}

.remove {
  height: 13px;
  width: 13px;
  background-size: 13px 13px;
  color: #F2F2F2;
  background-image: url("data:image/svg+xml;charset=utf8,%3C?xml version='1.0' encoding='UTF-8'?%3E%3Csvg width='13px' height='13px' viewBox='0 0 13 13' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'%3E%3C!-- Generator: sketchtool 49.1 (51147) - http://www.bohemiancoding.com/sketch --%3E%3Ctitle%3E1333134D-473B-4606-A178-F5570BA281E8%3C/title%3E%3Cdesc%3ECreated with sketchtool.%3C/desc%3E%3Cdefs%3E%3Cpath d='M8.62132034,6.5 L12.5104076,2.6109127 C13.0961941,2.02512627 13.0961941,1.0753788 12.5104076,0.48959236 C11.9246212,-0.0961940777 10.9748737,-0.0961940777 10.3890873,0.48959236 L6.5,4.37867966 L2.6109127,0.48959236 C2.02512627,-0.0961940777 1.0753788,-0.0961940777 0.48959236,0.48959236 C-0.0961940777,1.0753788 -0.0961940777,2.02512627 0.48959236,2.6109127 L4.37867966,6.5 L0.48959236,10.3890873 C-0.0961940777,10.9748737 -0.0961940777,11.9246212 0.48959236,12.5104076 C1.0753788,13.0961941 2.02512627,13.0961941 2.6109127,12.5104076 L6.5,8.62132034 L10.3890873,12.5104076 C10.9748737,13.0961941 11.9246212,13.0961941 12.5104076,12.5104076 C13.0961941,11.9246212 13.0961941,10.9748737 12.5104076,10.3890873 L8.62132034,6.5 Z' id='path-1'%3E%3C/path%3E%3C/defs%3E%3Cg id='Symbols' stroke='none' stroke-width='1' fill='none' fill-rule='evenodd'%3E%3Cg id='Icons/Close' transform='translate(-4.000000, -4.000000)'%3E%3Cg id='icon' transform='translate(4.000000, 4.000000)'%3E%3Cmask id='mask-2' fill='white'%3E%3Cuse xlink:href='%23path-1'%3E%3C/use%3E%3C/mask%3E%3Cuse id='Close' fill='%23F4F4F4' xlink:href='%23path-1'%3E%3C/use%3E%3C/g%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
}
`;
